name: Build and Release macOS DMG

on:
  push:
    tags:
      - 'v*.*.*'  # 当推送符合此模式的标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: '18.12'  # 指定 Node.js 版本

      - name: 安装 pnpm
        run: npm install -g pnpm

      - name: 安装项目依赖
        run: pnpm install

      - name: 设置 Rust 环境
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: 安装 Tauri CLI
        run: cargo install tauri-cli

      - name: 构建 Tauri 应用
        run: pnpm run tauri build

      - name: 创建 DMG 文件
        run: |
          # 安装 create-dmg 工具
          brew install create-dmg
          # 创建 DMG 文件，指定输出文件名和源文件夹路径
          create-dmg \
            --volname "MilkyWarp" \
            --skip-jenkins \
            MilkyWarp.dmg \
            src-tauri/target/release/bundle/macos/MilkyWarp.app

      - name: 创建 GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上传 DMG 到 Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MilkyWarp.dmg
          asset_name: MilkyWarp.dmg
          asset_content_type: application/x-apple-diskimage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
